services:
  mongodb:
    image: mongo:7.0
    container_name: certshield-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: certshield-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=certshield
      - API_KEY=change-me
      - VERIFY_BASE_URL=http://localhost:3001/v
      - INSTITUTION_NAME=CertShield Institution
      - PRIVATE_KEY_PATH=keys/private_key.pem
      - PUBLIC_KEY_PATH=keys/public_key.pem
      - KEY_ID=key-2026-01
    depends_on:
      - mongodb
    volumes:
      - ./backend/keys:/app/keys

volumes:
  mongo_data:
